export const CREATE_POST = "CREATE_POST";

export const GET_POST_SUCCESS = "GET_POST";

export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";

export const BEGIN_API_CALL = "BEGIN_API_CALL";

export const SAVE_COMMENT_SUCCESS = "SAVE_COMMENT";

export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";

export const USER_SIGNOUT_SUCCESS = "USER_SIGNOUT_SUCCESS";

export const USER_VERIFY_TOKEN_SUCCESS = "USER_VERIFY_TOKEN_SUCCESS";

export const SAVE_POST_SUCCESS = "SAVE_POST_SUCCESS";

export const OPEN_ERROR_NOTIFICATION = "OPEN_ERROR_NOTIFICATION";
export const OPEN_SUCCESS_NOTIFICATION = "OPEN_SUCCESS_NOTIFICATION";
export const CLOSE_NOTIFICATION = "CLOSE_NOTIFICATION";

export const SAVE_LIKE_POST_SUCCESS = "SAVE_LIKE_POST_SUCCESS";

export const SAVE_LIKE_POST_FAIL = "SAVE_LIKE_POST_FAIL";

export const SAVE_VIEW_POST_SUCCESS = "SAVE_VIEW_POST_SUCCESS";

export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
